languageCode = "de-de"
title = "GardenPiratez"
baseURL = "/"
themesDir = "themes"
theme = "gardenpiratez"

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

[params]
google_analytics_id = "G-3RMB2QE675"

[params.homepage_meta_tags]
meta_description = ""
meta_og_title = ""
meta_og_type = "website"
meta_og_url = "https://gardenpiratez.de"
meta_og_image = ""
meta_og_description = ""
meta_twitter_card = "summary"
meta_twitter_site = "@gardenpiratez"
meta_twitter_creator = "@gardenpiratez"

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Services"
url = "/services/"
weight = 2

[[menu.main]]
name = "Networks"
url = "/networks/"
weight = 3

[[menu.main]]
name = "History"
url = "/history/"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5

[permalinks]
post = "/:year/:month/:day/:slug/"
pages = "/:filename/"
