name = "GardenPiratez"
license = ""
licenselink = "NO LICENSE"
description = "Portfolio"

homepage = "https://gardenpiratez.de"
demosite = "https://gardenpiratez.de"

tags = ["responsive","minimal","clean","company","portfolio","bootstrap"]
features = ["services","work","fullwidth","hero images"]

[author]
  name = ""
  homepage = "https://www.gardenpiratez.de"
